### PR TITLE
chore: removed z-index of image 38

### PR DESCRIPTION
**Pull request by GauravBurande**
closes issue: https://github.com/Atri-Labs/atrilabs-engine/issues/662

### CODE REVIEW

**Comment by GauravBurande** [comment]
atri error

After running the atri start command, I opened the webapp on port 4002 but the editor was blank, can anyone please explain why it wasn't displaying the site and the highlighted error.

**Comment by cruxcode** [comment]
> atri error
> 
> After running the atri start command, I opened the webapp on port 4002 but the editor was blank, can anyone please explain why it wasn't displaying the site and the highlighted error.

Are you not running the editor locally?

**Comment by GauravBurande** [comment]
> 

I'm using codespaces

**Comment by GauravBurande** [comment]
> > atri error
> > After running the atri start command, I opened the webapp on port 4002 but the editor was blank, can anyone please explain why it wasn't displaying the site and the highlighted error.
> 
> Are you not running the editor locally?

running it locally fixed the problem.

**Pull request closed without merging**
